#!/bin/bash
# Created by Franco Loyola - For Noroff Final Degree Project
# For the demo.sh

message="This is the line"
file1="test1.log"
file2="test2.log"

nLines=200

for ((i = 0 ; i <= nLines ; i++))
do
    echo "$message $i generated by the file writer script. $file1" >> ../build/$file1
    echo "$message $i generated by the file writer script. $file2" >> ../build/$file2
    sleep 0.1
    if [[ $i -eq $nLines ]]
    then
        echo "Appended $nLines to $file1 and $file2"
    fi
done
